#!/usr/bin/env python3
"""Prepare deterministic Context build skeletons from Manifest tasks."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any

from .audit import ManifestTask, relpath
from .fingerprint import generate_fingerprints, yaml_quote
from .manifest import parse_statuses, select_tasks, task_to_dict


@dataclass
class PlannedWrite:
    target: Path
    action: str
    content: str


def title_from_task(task: ManifestTask) -> str:
    raw = task.fields.get("Title") or task.task_id or task.name
    return " ".join(part.capitalize() for part in raw.replace("_", "-").split("-") if part)


def source_mode(fingerprints: list[dict[str, Any]]) -> str:
    states = {str(item.get("worktree")) for item in fingerprints}
    if not states:
        return "unknown"
    if states == {"clean"}:
        return "clean"
    if states == {"dirty"}:
        return "dirty"
    if states == {"untracked"}:
        return "untracked"
    return "mixed"


def yaml_list(values: list[str]) -> str:
    return "[" + ", ".join(json.dumps(value) for value in values) + "]"


def render_fingerprints(fingerprints: list[dict[str, Any]]) -> list[str]:
    lines: list[str] = []
    for item in fingerprints:
        lines.append(f"  - file: {yaml_quote(item.get('file'))}")
        lines.append(f"    commit: {yaml_quote(item.get('commit'))}")
        lines.append(f"    tracked: {yaml_quote(item.get('tracked'))}")
        lines.append(f"    worktree: {yaml_quote(item.get('worktree'))}")
        lines.append(f"    contentHash: {yaml_quote(item.get('contentHash'))}")
    return lines


def render_context(task: ManifestTask, fingerprints: list[dict[str, Any]], draft: bool) -> str:
    title = title_from_task(task)
    lines = [
        "---",
        f"id: {yaml_quote(task.task_id)}",
        f"title: {yaml_quote(title)}",
        'status: "planned"',
        "notAuthoritative: true",
        "fingerprint:",
        *render_fingerprints(fingerprints),
        f"tags: {yaml_list(task.tags)}",
        "---",
        "",
        f"# {title}",
        "",
        "## Role",
        "",
        "TODO: Replace this skeleton with the module responsibility map before marking the Manifest task built.",
        "",
        "## Contracts",
        "",
        "- Public API or cross-module contract: TODO",
        "- Inputs and outputs: TODO",
        "- Error and boundary behavior: TODO",
        "",
        "## Design Notes",
        "",
        "TODO: Capture non-obvious trade-offs and why the current shape exists.",
        "",
        "## Interactions",
        "",
        "TODO: Add Mermaid only when it clarifies a multi-step interaction.",
        "",
        "## SSOT Links",
        "",
        "- Source files: " + ", ".join(f"`{source}`" for source in task.sources),
        "",
        "## Blindspots",
        "",
        "- Skeleton generated by `dev-cycle context build-assist`; not authoritative.",
    ]
    if draft:
        lines.append("- Draft target was requested; move to the planned Context path only after source is clean and content is reviewed.")
    return "\n".join(lines).rstrip() + "\n"


def render_validation(task: ManifestTask, context_path: str, fingerprints: list[dict[str, Any]]) -> str:
    return f"""# Validation: {task.task_id}

- **Context**: `{context_path}`
- **Source Mode**: `{source_mode(fingerprints)}`
- **Validated At**: `{date.today().isoformat()}`

## Questions

### Q1 Architecture

- **Question**: Which modules own the main responsibility described by this Context?
- **Context-only Answer**: TODO
- **Citations**: `{context_path}`
- **Result**: pending

### Q2 Boundary

- **Question**: What are the important input, output, and failure boundaries?
- **Context-only Answer**: TODO
- **Citations**: `{context_path}`
- **Result**: pending

## Blindspots

- Skeleton generated by `dev-cycle context build-assist`; replace pending answers before marking the Manifest task built.
"""


def target_context_path(task: ManifestTask, draft: bool) -> str | None:
    if draft:
        return f".dev-cycle/context/_draft/{task.task_id}.md"
    return task.context


def plan_write(path: Path, content: str, force: bool) -> PlannedWrite:
    if path.exists() and not force:
        return PlannedWrite(path, "skip", content)
    if path.exists() and force:
        return PlannedWrite(path, "overwrite", content)
    return PlannedWrite(path, "write", content)


def apply_write(write: PlannedWrite) -> None:
    if write.action == "skip":
        return
    write.target.parent.mkdir(parents=True, exist_ok=True)
    write.target.write_text(write.content, encoding="utf-8")


def task_plan(
    repo: Path,
    task: ManifestTask,
    allow_dirty: bool,
    allow_untracked: bool,
    draft: bool,
    force: bool,
) -> dict[str, Any]:
    target_context = target_context_path(task, draft)
    validation = f".dev-cycle/context/_validation/{task.task_id}.md"
    blocked_reasons: list[str] = []
    if not target_context:
        blocked_reasons.append("task missing Context field")
    if not task.sources:
        blocked_reasons.append("task missing Sources field")

    fingerprints, errors, _ = generate_fingerprints(
        repo,
        task.sources,
        allow_dirty or draft,
        allow_untracked or draft,
    )
    blocked_reasons.extend(errors)
    allowed = not blocked_reasons
    writes: list[PlannedWrite] = []
    if target_context:
        writes.append(
            plan_write(
                repo / target_context,
                render_context(task, fingerprints, draft),
                force,
            )
        )
        writes.append(
            plan_write(
                repo / validation,
                render_validation(task, target_context, fingerprints),
                force,
            )
        )
    return {
        "task": task_to_dict(task),
        "targetContext": target_context,
        "validation": validation,
        "draft": draft,
        "allowed": allowed,
        "blockedReasons": blocked_reasons,
        "fingerprints": fingerprints,
        "writes": [
            {
                "path": relpath(write.target, repo),
                "action": write.action,
            }
            for write in writes
        ],
        "_writes": writes,
    }


def public_plan(plan: dict[str, Any]) -> dict[str, Any]:
    return {key: value for key, value in plan.items() if key != "_writes"}


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default=".", help="Target repository root.")
    parser.add_argument("--manifest", default="CONTEXT_PLAN.md", help="Manifest path.")
    parser.add_argument("--slice", type=int, default=1, help="Maximum tasks to prepare.")
    parser.add_argument(
        "--only",
        action="append",
        default=[],
        help="Restrict to task id, name, tag, Context path, or source path. May be repeated.",
    )
    parser.add_argument(
        "--status",
        action="append",
        default=[],
        help="Restrict by Manifest status. Defaults to planned and stale.",
    )
    parser.add_argument("--draft", action="store_true", help="Write skeletons under _draft.")
    parser.add_argument(
        "--allow-dirty",
        action="store_true",
        help="Allow dirty tracked and untracked sources in generated fingerprints.",
    )
    parser.add_argument(
        "--allow-untracked",
        action="store_true",
        help="Allow untracked sources without allowing dirty tracked sources.",
    )
    parser.add_argument("--force", action="store_true", help="Overwrite existing skeleton files.")
    parser.add_argument("--write", action="store_true", help="Write planned skeleton files.")
    parser.add_argument("--json", action="store_true", help="Print machine-readable JSON.")
    return parser.parse_args(argv)


def print_text(data: dict[str, Any]) -> None:
    mode = "write" if data["write"] else "dry-run"
    print("# Context Build Assist")
    print()
    print(f"- Mode: {mode}")
    print(f"- Selected tasks: {len(data['plans'])}")
    print(f"- Blocked tasks: {len(data['blocked'])}")
    for plan in data["plans"]:
        status = "allowed" if plan["allowed"] else "blocked"
        print()
        print(f"## {plan['task']['id']} ({status})")
        if plan["targetContext"]:
            print(f"- Context: `{plan['targetContext']}`")
        print(f"- Validation: `{plan['validation']}`")
        for reason in plan["blockedReasons"]:
            print(f"- Blocked: {reason}")
        for write in plan["writes"]:
            print(f"- {write['action'].upper()} {write['path']}")


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    repo = Path(args.repo).resolve()
    if not repo.exists() or not repo.is_dir():
        print(f"repo does not exist: {repo}", file=sys.stderr)
        return 2
    if args.slice < 1:
        print("--slice must be at least 1", file=sys.stderr)
        return 2
    manifest = Path(args.manifest)
    if not manifest.is_absolute():
        manifest = repo / manifest
    manifest = manifest.resolve()
    if not manifest.exists() or not manifest.is_file():
        print(f"manifest does not exist: {manifest}", file=sys.stderr)
        return 2
    try:
        statuses = parse_statuses(args.status)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    selection = select_tasks(manifest, statuses, args.only, args.slice)
    plans = [
        task_plan(
            repo,
            task,
            args.allow_dirty,
            args.allow_untracked,
            args.draft,
            args.force,
        )
        for task in selection.selected
    ]
    blocked = [plan for plan in plans if not plan["allowed"]]
    if args.write:
        for plan in plans:
            if not plan["allowed"]:
                continue
            for write in plan["_writes"]:
                apply_write(write)
    data = {
        "schemaVersion": 1,
        "repo": str(repo),
        "manifest": relpath(manifest, repo),
        "write": args.write,
        "slice": args.slice,
        "selectedCount": len(plans),
        "warnings": selection.warnings,
        "plans": [public_plan(plan) for plan in plans],
        "blocked": [public_plan(plan) for plan in blocked],
    }
    if args.json:
        print(json.dumps(data, indent=2, sort_keys=True))
    else:
        print_text(data)
    return 1 if blocked else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
